= Project Proposal
Oliver Schatzberger
1.0.2, 2021-11-11: Notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektantrag Oliver Schatzberger


=== Kinoreservierungssystem
Ich möchte gerne ein Projekt erstellen mit welchem man Plätze für Kinos reservieren kann. Ein Reservierungssystem mit GUI. Es sollte dem User außerdem möglich sein extra Angebote zu buchen. 


=== Technologien
* Java
* JavaFX
* Maven

=== Funktion
Der User soll einen Platz auswählen können auf einer Karte die in Kategorien untergeordnet ist. Er soll außerdem persönliche Daten angeben, anhand dieser wird dann der Preis berechnet. Außerdem will ich eine Login Funktion einbauen für wiederkehrende Nutzer.

=== Motivation
Ich möchte zum ersten Mal mit JavaFX arbeiten und so ein GUI erstellen. Ich will mich auch mit der Login Funktion beschäftigen um ein brauchbares System zu erstellen.

test


